# globals.R
utils::globalVariables(c(
  "..col_tmp", "..cols_to_keep", "..fields_to_parse", "..final_col",
  "Accepted_family", "Accepted_name", "Accepted_name_author", "Accepted_name_id",
  "Accepted_name_rank", "Author_matched", "COUNTRY_INVALID", "Ctrl_basisOfRecord",
  "Ctrl_catalogNumber", "Ctrl_coordinates_validated_by_gbif_issue",
  "Ctrl_countryCode", "Ctrl_decimalLatitude", "Ctrl_decimalLongitude",
  "Ctrl_eventDate", "Ctrl_family", "Ctrl_fieldNotes", "Ctrl_gbifID",
  "Ctrl_geospatial_quality", "Ctrl_hasCoordinate", "Ctrl_institutionCode",
  "Ctrl_issue", "Ctrl_key", "Ctrl_locality", "Ctrl_month",
  "Ctrl_moreInformativeRecord", "Ctrl_municipality", "Ctrl_identifiedBy",
  "Ctrl_nameRecordedBy_Standard", "Ctrl_recordNumber",
  "Ctrl_recordNumber_Standard", "Ctrl_recordedBy", "Ctrl_scientificName",
  "Ctrl_stateProvince", "Ctrl_taxonRank", "Ctrl_verbatim_quality", "Ctrl_year",
  "FAMILY__", "FAMILY__recordNumber", "FAMILY_recordedBy_", "Key", "LEVEL3_COD", "N",
  "Name_matched", "Name_matched_id", "Name_submitted", "Records", "Taxonomic_status",
  "UltraGBIF_dataset_result", "UltraGBIF_decimalLatitude",
  "UltraGBIF_decimalLongitude", "UltraGBIF_digital_voucher",
  "UltraGBIF_duplicates", "UltraGBIF_duplicates_grouping_status",
  "UltraGBIF_merged", "UltraGBIF_non_groupable_duplicates",
  "UltraGBIF_num_duplicates", "UltraGBIF_number_taxon_names",
  "UltraGBIF_sample_taxon_name", "UltraGBIF_sample_taxon_name_status",
  "UltraGBIF_unidentified_sample", "UltraGBIF_useful_for_spatial_analysis",
  "UltraGBIF_wcvp_family", "UltraGBIF_wcvp_plant_name_id",
  "UltraGBIF_wcvp_taxon_name", "UltraGBIF_wcvp_taxon_status", "area_code_l3",
  "best_lat", "best_lon", "best_value", "clean_value", "constant", "coord_priority", "data",
  "extinct", "gbif_occurrence_file", "geohash", "grouping_pattern", "i.clean_value",
  "i.num_unique_taxa", "i.wcvp_plant_name_id", "i.wcvp_taxon_name", "introduced",
  "is_non_groupable", "location_doubtful", "max_info_score", "n_occ",
  "num_duplicates", "num_unique_taxa", "ori_sp_name", "ref_wcvp_names", "tem_COUNTRY",
  "tem_catalogNumber", "tem_fieldNotes", "tem_institutionCode", "tem_locality",
  "tem_municipality", "tem_recordNumber", "tem_recordedBy", "tem_stateProvince",
  "tem_year", "wcvp_accepted_plant_name_id", "wcvp_area_status",
  "wcvp_distributions", "wcvp_family", "wcvp_plant_name_id", "wcvp_reviewed",
  "wcvp_searchNotes", "wcvp_searchedName", "wcvp_taxon_authors",
  "wcvp_taxon_authors_of_searchedName", "wcvp_taxon_name", "wcvp_taxon_rank",
  "wcvp_taxon_status", "wcvp_taxon_status_of_searchedName",
  "wcvp_verified_author", "wcvp_verified_speciesName", "wgsrpd3",".","taxon_name"
))
